### ISSUE TITLE
RpbIndexReq returns unexpected response. [JIRA: RIAK-2269]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak_kv#1263]
https://github.com/basho/riak_pb/blob/end-to-end/timeseries/src/riak_kv.proto#L176

To reproduce:
- Build Riak TS from current `end-to-end/timeseries` branch.
- Run specific Node.js client test. Prerequisites are `npm` and `node` installed:

```
git clone git://github.com/basho/riak-nodejs-client
cd riak-nodejs-client
git checkout --track origin/features/lrb/rts-311
npm install
./node_modules/.bin/mocha --no-colors ./test/integration/kv/secondaryindexquery.js
```

You will see error messages like the following:

```
5) Secondary Index Query - Integration Should set a coninuation on a paginated query:

      Uncaught AssertionError: [RiakNode] node (riak-test:10017): incorrect response code; expected 26, received 42
      + expected - actual

      -false
      +true

      at SecondaryIndexQuery.callback (test/integration/kv/secondaryindexquery.js:179:13)
      at SecondaryIndexQuery.CommandBase._callback (lib/commands/commandbase.js:62:19)
      at SecondaryIndexQuery.CommandBase.onError (lib/commands/commandbase.js:159:10)
      at lib/core/riaknode.js:250:21
      at RiakNode._maybeRetryCommand (lib/core/riaknode.js:356:9)
      at RiakNode._responseReceived (lib/core/riaknode.js:249:14)
      at RiakConnection._receiveData (lib/core/riakconnection.js:215:14)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
```

The test sets [`return_terms` to `true` on the `RpbIndexReq`](https://github.com/basho/riak_pb/blob/end-to-end/timeseries/src/riak_kv.proto#L176) and expects an `RpbIndexResp` back (code 26). It also sets `stream` to `true`.

**Comment by macintux** [comment]
It looks like there's an empty result set with the wrong message type sent at the end of streaming results; everything else looks reasonable as far as I can tell from my testing with the Erlang client.

**Comment by macintux** [comment]
```
47> f(Results), {ok, Results} = riakc_pb_socket:get_index_range(Pid, <<"bucket3">>, <<"email_bin">>, <<"a">>, <<"z">>, [{return_term, true}, {max_results, 5}, {stream, true}]).
{ok,36814}
48> flush().
Shell got {36814,
           {index_stream_result_v1,[<<"key0">>,<<"key1">>,<<"key10">>,
                                    <<"key11">>,<<"key12">>],
                                   undefined}}
Shell got {36814,{ok,{index_stream_body_result_v1,[]}}}
Shell got {36814,{done,<<"g2gCbQAAAApqZEBlcGVwLnVzbQAAAAVrZXkxMg==">>}}
```

**Comment by macintux** [comment]
Example:

```
47> f(Results), {ok, Results} = riakc_pb_socket:get_index_range(Pid, <<"bucket3">>, <<"email_bin">>, <<"a">>, <<"z">>, [{return_term, true}, {max_results, 5}, {stream, true}]).
{ok,36814}
48> flush().
Shell got {36814,
           {index_stream_result_v1,[<<"key0">>,<<"key1">>,<<"key10">>,
                                    <<"key11">>,<<"key12">>],
                                   undefined}}
Shell got {36814,{ok,{index_stream_body_result_v1,[]}}}
Shell got {36814,{done,<<"g2gCbQAAAApqZEBlcGVwLnVzbQAAAAVrZXkxMg==">>}}
```

**Comment by macintux** [comment]
Should be seeing index terms returned there too, not sure what to make of that.

**Comment by lukebakken** [comment]
Thanks for looking at this. Let me know if I can help.

**Comment by macintux** [comment]
ah, `return_terms` (plural), so that mystery at least is solved.

**Comment by macintux** [comment]
PR filed @lukebakken.  Thanks again for the good catch.
